# Generated by Django 5.2 on 2025-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('broadcaster', 'Broadcaster'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
