# Generated by Django 5.2 on 2025-04-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_app', '0002_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('broadcaster', 'Broadcaster'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
