# Generated by Django 5.2 on 2025-04-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_app', '0003_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorization_id',
            field=models.ImageField(blank=True, null=True, upload_to='authorization_ids/'),
        ),
    ]
