# Generated by Django 5.2 on 2025-04-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_app', '0005_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('broadcaster', 'Broadcaster')], max_length=20),
        ),
    ]
