# Generated by Django 5.2 on 2025-04-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_app', '0007_remove_broadcast_stream_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='description',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='is_live',
        ),
    ]
