# Generated by Django 5.2 on 2025-04-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_app', '0008_remove_broadcast_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
