# Generated by Django 5.2 on 2025-04-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_app', '0009_broadcast_description_broadcast_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
